### ISSUE TITLE
Macros 

### ISSUE THREAD

**Issue by brianteeman** [helo-head/Tally-Core2#8]
> void updateMacroButton(int buttonNumber, int macroOffset, bool isPressed, bool isRunning) {

If I am reading this correctly then the button text and the button color should change when a macro button is pressed

From what I can tell they never change from TFT_DARKGREY and WHITE

**Comment by helo-head** [comment]
Ill take a quick look at it but I will not have access to an ATEM till next week so it might be a bit before its fixed. Can you at least confirm the macro is running?

**Comment by brianteeman** [comment]
Yes the macro runs - maybe the problem is with  
updateMacroButton(buttonNumber, macroOffset, **tbtn.isPressed**(), false);

**Comment by helo-head** [comment]
They changed a lot of the touch library behavior so I will have to go back in the older touch library and figure out what happened to isPressed as well as TE_BTNONLY.

**Comment by helo-head** [comment]
Based on the new Touch header, although isPressed is supposedly still supported its use is discouraged. As such Im going to look at other alternative solutions. At lease this is something I can work on with an ATEM ...

**Comment by helo-head** [comment]
Its good that you caught this as it also helped to identify a couple of other  problems. The first I noticed was that if the code had worked the macro button status would never have been reset after a button push. The second issue is that since the handler is capturing RELEASE the buttonWasPressed code fires multiple times for single button press (TOUCH and RELEASE). So I need to either move the RELEASE event to a separate handler or fix the buttonWasPressed code to consider the event.type. Im also not a big fan of capturing TAP as it appears a tap will often generate both a touch and tap event leading to multiple events.

**Comment by brianteeman** [comment]
Maybe the answer they gave me here will help
https://github.com/m5stack/M5Core2/issues/120

**Comment by helo-head** [comment]
After two years I was finally able to get the GitHub desktop to work on my M1 Mac Mini. It's nice to be able to do much of the work on my mac vs trying to do everything on my Pi development platform. Editing all the code in the Arduino ide was painful.
